// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDn8dOf2-tWeJgWi0MqOvFoJCddigpOE-s',
    appId: '1:909131430306:web:0d3d23fb89025fea439afb',
    messagingSenderId: '909131430306',
    projectId: 'bazar-app-b6217',
    authDomain: 'bazar-app-b6217.firebaseapp.com',
    storageBucket: 'bazar-app-b6217.firebasestorage.app',
    measurementId: 'G-ZBSQRZ0HTL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAL7zS85J9qE91ohunkr_LLOouF_GWTlS4',
    appId: '1:909131430306:android:42ad006ddc02d3be439afb',
    messagingSenderId: '909131430306',
    projectId: 'bazar-app-b6217',
    storageBucket: 'bazar-app-b6217.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDj4lXLNTeQ5OOlmfTACzjbISKL_NtLlNI',
    appId: '1:909131430306:ios:ceac2031d06ce53f439afb',
    messagingSenderId: '909131430306',
    projectId: 'bazar-app-b6217',
    storageBucket: 'bazar-app-b6217.firebasestorage.app',
    iosBundleId: 'com.example.bazarGroup1',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDj4lXLNTeQ5OOlmfTACzjbISKL_NtLlNI',
    appId: '1:909131430306:ios:ceac2031d06ce53f439afb',
    messagingSenderId: '909131430306',
    projectId: 'bazar-app-b6217',
    storageBucket: 'bazar-app-b6217.firebasestorage.app',
    iosBundleId: 'com.example.bazarGroup1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDn8dOf2-tWeJgWi0MqOvFoJCddigpOE-s',
    appId: '1:909131430306:web:438e6c0cda7a3b63439afb',
    messagingSenderId: '909131430306',
    projectId: 'bazar-app-b6217',
    authDomain: 'bazar-app-b6217.firebaseapp.com',
    storageBucket: 'bazar-app-b6217.firebasestorage.app',
    measurementId: 'G-P0HHGEF6FE',
  );
}
